const heading=document.getElementById("main-heading")
heading.textContent="fruit_world";
heading.style.color="orange";
heading.style.backgroundColor="green";
const header=document.getElementById("header");
header.style.borderBottom="3px solid orange";
const basketheading=document.getElementById("basket-heading");
basketheading.style.color="green";
const thanksgiving=document.getElementById("thanks");
thanksgiving.innerHTML="<p>thanks for visisting us!</p>"